

server:
#  port: 8080
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/sbip.p12
    key-store-password: ${keystore}
    key-alias: sbip
  port: 8443

testing:
  condition: yeppee
  condition2: yeppee2

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, releaseNotes, prometheus
#        exclude: threaddump,heapdump
      # changing actuator context path
      base-path: /sbip
      # changing actuator endpoint path e.g health to appHealth :: -> http://localhost:8081/sbip/appHealth
      path-mapping:
        health: appHealth
  # displaying management endpoint details
  endpoint:
    health:
      show-details: always
    # always, never, when_authorized
      # the extra details will show when the endpoint is authorized carrying the role read or update
#      show-details: when_authorized
#      roles: read,update
  info:
    env:
      enabled: true
    build:
      enabled: true
    os:
      enabled: true
  # changing actuator port away from application port
  server:
    port: 8081
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans

  tracing:
    sampling:
      probability: 1.0
  metrics:
    tags:
      application:

info:
  build:
    artifact: '@project.artifactId@'
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
    properties.java.version: '@java.version@'


# Course Tracker
spring:

  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
      # very key property for h2
    defer-datasource-initialization: true
  datasource:
    username: sa
    password: password
    url: jdbc:h2:mem:userdb
    driver-class-name: org.h2.Driver
  ldap:
    embedded:
      port: 8389
      ldif: classpath:users.ldif
      base-dn: dc=manning,dc=com


  cloud:
    vault:
      token: ${VAULT_TOKEN}
      authentication: token
      host: localhost
      port: 8200
      scheme: http
  config:
    import: vault://secret/coursetracker

  application:
    name: coursetracker


