spring:
  boot:
    admin:
      client:
        url: http://localhost:9090
        username:
        password:
  application:
    name: client-for-admin-server

management:
  endpoints:
    web:
      exposure:
        include: '*'
      #        exclude: threaddump,heapdump
      # changing actuator context path
      #      base-path: /sbip
      # changing actuator endpoint path e.g health to appHealth :: -> http://localhost:8081/sbip/appHealth
      path-mapping:
        health: appHealth
  # displaying management endpoint details
  endpoint:
    health:
      show-details: always
      # always, never, when_authorized
      # the extra details will show when the endpoint is authorized carrying the role read or update
  #      show-details: when_authorized
  #      roles: read,update
  info:
    env:
      enabled: true
    build:
      enabled: true
    os:
      enabled: true
