apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-reg-deploy
  name: user-reg-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-reg-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: user-reg-deploy
    spec:
      containers:
      - image: zikozee/user-reg-kubernetes:0.0.1-SNAPSHOT
        name: user-reg-kubernetes
        resources: {}
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          httpGet:
            path: /sbip/health/livenessState
            port: 8080
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          httpGet:
            path: /sbip/health/readinessState
            port: 8080

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-reg-deploy
  name: user-reg-service
spec:
  ports:
    - nodePort: 30007
      protocol: TCP
      targetPort: 8080
      port: 8080
  selector:
    app: user-reg-deploy
  type: NodePort
