
spring:

  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
      # very key property for h2
    defer-datasource-initialization: true
  datasource:
    username: sa
    password: password
    url: jdbc:h2:mem:userdb
    driver-class-name: org.h2.Driver