
spring:

  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
      # very key property for h2
    defer-datasource-initialization: true
  datasource:
    username: sa
    password: password
    url: jdbc:h2:mem:userdb
    driver-class-name: org.h2.Driver
  mvc:
    static-path-pattern: /swagger*

app:
  description: Spring Boot Course Tracker API
  version: v1


management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
      base-path: /sbip
  endpoint:
    health:
      show-details: always